### ISSUE TITLE
Errors when running CRISPRloci_standalone

### ISSUE THREAD

**Issue by rfarouni** [BackofenLab/CRISPRloci#2] opened 2021-07-01 09:08 UTC
When I run `python3.7 CRISPRloci_standalone.py -f Example/NC_005230.fasta -st dna` I get this error

`FileNotFoundError: [Errno 2] No such file or directory: '/home/rick/Documents/CRISPRloci-1.0.0/CRISPRcasIdentifier/HMM_sets/HMM2019'`

It seems that the "HMM_sets" and "trained_models" directories end up under `./CRISPRloci-1.0.0 `instead of `./CRISPRloci-1.0.0/CRISPRcasIdentifier`. When I unzip the two files in that CRISPRcasIdentifier directory first, the program runs, but another error message appears 

```CRISPR_3 consensus
GUCUCCACUCGUAGGAGAAAUUAAUUGAUUGGAAAC
.(((((.......))))).................. ( -6.00)
.({(((,.,,...}}}}}..,,...,,,.,,,,... [ -6.52]
.(((((.......))))).................. { -6.00 d=6.14}
 frequency of mfe structure in ensemble 0.431482; ensemble diversity 8.13  
rm: cannot remove '/home/rick/Documents/CRISPRloci-1.0.0/TMP//*.*': No such file or directory```

**Comment by Alexander-Mitrofanov** [comment] 2021-07-01 09:12
Hello Rick,

Thank you for using the CRISPRloci and the issue report.
The problem will be fixed soon.

Best,
Alex

**Comment by Edison2021** [comment] 2021-09-06 02:16
Hi Alex
Is the problem fixed?

Thanks
Edison

**Comment by Alexander-Mitrofanov** [comment] 2021-09-06 11:03
The problem is fixed now.

**Closed by Alexander-Mitrofanov** 2021-09-06 11:03 UTC
